### PR TITLE
add id tag in _algorithms.md

### PR DESCRIPTION
**Pull request by lemonez**
Add tag to be able to link to this from from other docs.

### CODE REVIEW

**Review by bnlb — APPROVED** [review]
👍

**Comment by lemonez** [comment]
@bnlb I think I'm still not able to merge this even though you added me as a code owner?

**Comment by bnlb** [comment]
Ooops, I added you as an owner in dev-center, but forgot about this repo. I'll add you as an owner here too.

**Comment by lemonez** [comment]
Ah got it. Thanks!

**Pull request merged**
